---
dependencies:
  - role: handlers

  - role: certificates
    cert_options: "{{ swarm_cert_options }}"

  # Open the Docker API to the network.
  - role: docker
    docker_network_options: "{{ swarm_docker_daemon_options }}"
